# This is a basic workflow to help you get started with Actions

name: Build test reports list

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "test-reports" branch
  push:
    branches: [ "test-reports" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup test report list index.html (see https://gist.github.com/mklabs/a0219dedb01498bde4a054f90d7f66dd)
        run: |
          curl https://gist.githubusercontent.com/mklabs/a0219dedb01498bde4a054f90d7f66dd/raw/81a2f0fdea12d90a38fa3e6021ae364bc0afc670/generate-html.js > generate-html.js
          curl https://gist.githubusercontent.com/mklabs/a0219dedb01498bde4a054f90d7f66dd/raw/81a2f0fdea12d90a38fa3e6021ae364bc0afc670/generate-readme.js > generate-readme.js
          node generate-html.js > index.html
          node generate-readme.js > readme.md
          rm generate-html.js
          rm generate-readme.js
          
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
